---
- name: Install dependencies.
  dnf:
    name: '{{ item }}'
    state: present
  with_items:
    - libpq-devel
    - nc
    - git
    - python-setuptools

- name: Install Python dependencies.
  pip: 
    name: "{{ item }}"
    executable: /usr/local/bin/pip3.11
  with_items:
    - setuptools
    - Flask
    - flask-migrate
    - SQLAlchemy
    - psycopg2
    - flask_login
