---
- name: Include python task.
  include_tasks:
    file: python.yaml

- name: Include init task.
  include_tasks:
    file: init.yaml

- name: Include disable SElinux task.
  include_tasks:
    file: disable_selinux.yaml

- name: Include Postgres task.
  include_tasks:
    file: postgres.yaml

- name: Include dependencies task.
  include_tasks:
    file: dependencies.yaml

- name: Include create database task.
  include_tasks:
    file: create_database.yaml

- name: Include deploy app task.
  include_tasks:
    file: deploy_app.yaml
