---
- name: Install PostgreSQL.
  yum:
    name: ['postgresql', 'postgresql-server']
    state: present

- name: Find out if PostgreSQL is initialized.
  stat:
    path: "{{ pg_hba }}"
  register: postgres_data 

- name: Initialize PostgreSQL.
  shell: "/usr/bin/postgresql-setup --initdb"
  when: not postgres_data.stat.exists

- name: Start PostgreSQL server.
  service: 
    name: postgresql
    state: started 
    enabled: yes

- name: Update listening adresses.
  lineinfile:
    path: '{{ pg_conf }}'
    regexp: "listen_addresses = 'localhost'"
    line: "listen_addresses = '*'"

- name: Update port.
  lineinfile:
    path: '{{ pg_conf }}'
    regexp: "port = 5432"
    line: "port = {{ db_port }}"

- name: Allow any host to connect (For testing). 
  lineinfile:
    path: '{{ pg_hba }}'
    regexp: "host    all             all             127.0.0.1/32            ident"
    line:   "host    all             all             127.0.0.1/32            trust"

- name: Restart PostgreSQL for changes to take effect.
  service:
    name: postgresql
    state: restarted
