---
- name: Install dependencies
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gcc 
    - openssl-devel
    - bzip2-devel 
    - libffi-devel 
    - zlib-devel 
    - tar 
    - wget 
    - make

- name: Create a directory for Python.
  file:
    path: /opt/python311
    state: directory

- name: Download and Unarchive Python 3.11.
  unarchive:
    src: https://www.python.org/ftp/python/3.11.1/Python-3.11.1.tgz
    dest: /opt/python311
    remote_src: yes

- name: Build and Compile Python3.11.
  shell: >
    cd /opt/python311/Python-3.11.1 &&
    ./configure --enable-optimizations &&
    make && make altinstall
